quantize_cfg = {
    "q_proj":{
        "type":"W8DX",
		"alpha":64
    },"k_proj":{
        "type":"W8DX",
		"alpha":64
    },"v_proj":{
        "type":"W8DX",
		"alpha":64
    },"o_proj":{
        "type":"W8DX",
		"alpha":64
    },"gate_proj":{
        "type":"W8DX",
		"alpha":64
    },"up_proj":{
        "type":"W8DX",
		"alpha":64
    },
    "down_proj":{
        "type":"W8DX",
        "alpha":256
    },
	"act_scales_path":"/root/zanilia/export_llama/act_scales/llama-2-7b.pt",
}